export const navItems = [
  {
    id: "1",
    label: "All producst",
    link: "/listing-item",
  },
  {
    id: "2",
    label: "All rooms",
    link: "#",
  },
  {
    id: "3",
    label: "Furnitures",
    link: "#",
  },
  {
    id: "4",
    label: "Interior",
    link: "#",
  },
  {
    id: "5",
    label: "Promotions of the week",
    link: "#",
  },
  {
    id: "6",
    label: "Garden",
    link: "#",
  },
  {
    id: "7",
    label: "Brands",
    link: "#",
  },
  {
    id: "8",
    label: "Customer newsletter",
    link: "#",
  },
  {
    id: "9",
    label: "Sale",
    link: "#",
  },
];

export const modeOfPayments = [
  {
    id: "01",
    name: "postnord",
    img: "/postnord-logo.png",
  },
  {
    id: "02",
    name: "visa",
    img: "/visa-logo.png",
  },
  {
    id: "03",
    name: "vepps",
    img: "/vepps-logo.png",
  },
];

export const pointers = [
  {
    id: "01",
    name: "Prislofte",
    img: "/cursor.png",
  },
  {
    id: "02",
    name: "Kjop og hent",
    img: "/cursor.png",
  },
  {
    id: "04",
    name: "Komfortgaranti",
    img: "/cursor.png",
  },
  {
    id: "05",
    name: "Finansiering",
    img: "/cursor.png",
  },
  {
    id: "06",
    name: "Apent kjop",
    img: "/cursor.png",
  },
];

export const banner1 = [{ id: "1", img: "/banner-one.jpg", alt: "hero-image" }];
export const banner2 = [{ id: "1", img: "/banner-two.jpg", alt: "hero-image" }];
export const sliderData2 = [
  {
    id: "1",
    price: "na 789",
    discounted: "na 123",
    img: "/minitable1.webp",
    alt: "imagt-alt",
    title: "Round Table",
    link: "/sofa",
    linkLabel: "click here",
  },
  {
    id: "2",
    price: "na 789",
    discounted: "na 123",
    img: "/minitable2.webp",
    alt: "imagt-alt",
    title: "Okayama Table",
    link: "/sofa",
    linkLabel: "click here",
  },
  {
    id: "3",
    price: "na 789",
    discounted: "na 123",
    img: "/minitable3.webp",
    alt: "imagt-alt",
    title: "Palma Table",
    link: "/sofa",
    linkLabel: "click here",
  },
  {
    id: "4",
    price: "na 789",
    discounted: "na 123",
    img: "/minitable2.webp",
    alt: "imagt-alt",
    title: "Calia Table",
    link: "/sofa",
    linkLabel: "click here",
  },
  {
    id: "5",
    price: "na 789",
    discounted: "na 123",
    img: "/minitable1.webp",
    alt: "imagt-alt",
    title: "Louis Table",
    link: "/sofa",
    linkLabel: "click here",
  },
  {
    id: "6",
    price: "na 789",
    discounted: "na 123",
    img: "/minitable3.webp",
    alt: "imagt-alt",
    title: "Cornos Table",
    link: "/sofa",
    linkLabel: "click here",
  },
  {
    id: "7",
    price: "na 789",
    discounted: "na 123",
    img: "/minitable2.webp",
    alt: "imagt-alt",
    title: "Woodstock Table",
    link: "/sofa",
    linkLabel: "click here",
  },
  {
    id: "8",
    price: "na 789",
    discounted: "na 123",
    img: "/minitable3.webp",
    alt: "imagt-alt",
    title: "Derby Table",
    link: "/sofa",
    linkLabel: "click here",
  },
];

export const sliderData = [
  {
    id: "1",
    price: "na 789",
    discounted: "na 123",
    img: "/lamp-a.webp",
    alt: "imagt-alt",
    title: "",
    link: "",
    linkLabel: "",
  },
  {
    id: "2",
    price: "na 789",
    discounted: "na 123",
    img: "/lamp-b.png",
    alt: "imagt-alt",
    title: "",
    link: "",
    linkLabel: "",
  },
  {
    id: "3",
    price: "na 789",
    discounted: "na 123",
    img: "/lamp-c.webp",
    alt: "imagt-alt",
    title: "",
    link: "",
    linkLabel: "",
  },
  {
    id: "4",
    price: "na 789",
    discounted: "na 123",
    img: "/lamp-a.webp",
    alt: "imagt-alt",
    title: "",
    link: "",
    linkLabel: "",
  },
  {
    id: "5",
    price: "na 789",
    discounted: "na 123",
    img: "/lamp-b.png",
    title: "",
    alt: "imagt-alt",
    link: "",
    linkLabel: "",
  },
  {
    id: "6",
    price: "na 789",
    discounted: "na 123",
    img: "/lamp-c.webp",
    title: "",
    alt: "imagt-alt",
    link: "",
    linkLabel: "",
  },
  {
    id: "7",
    price: "na 789",
    discounted: "na 123",
    img: "/lamp-b.png",
    alt: "imagt-alt",
    title: "",
    link: "",
    linkLabel: "",
  },
  {
    id: "8",
    price: "na 789",
    discounted: "na 123",
    img: "/lamp-c.webp",
    alt: "imagt-alt",
    title: "",
    link: "",
    linkLabel: "",
  },
];

export const imageItems = [
  {
    img: "/img1.webp",
    title: "Wood Craft Dining",
    price: "na 23.44",
    link: "click here",
  },
  {
    img: "/img4.webp",
    title: "Marte Dining",
    price: "na 23.44",
    link: "click here",
  },
  {
    img: "/img3.webp",
    title: "Malika Dining",
    price: "na 23.44",
    link: "click here",
  },
  {
    img: "/img2.webp",
    title: "Groove Dining",
    price: "na 23.44",
    link: "click here",
  },
];

export const imageItems2 = [
  {
    img: "/sofa4.webp",
    title: "Oslo Sofa",
    price: "na 23.44",
    link: "click here",
  },
  {
    img: "/sofa5.webp",
    title: "Cleaveland Sofa",
    price: "na 23.44",
    link: "click here",
  },
  {
    img: "/sofa8.webp",
    title: "Hedda Sofa",
    price: "na 23.44",
    link: "click here",
  },
];

export const products = [
  {
    id: "1",
    name: "Hejjen MOda",
    type: "dinning",
    price: "na 216",
    discounted: "na 166.50",
    sale: ["30%", "sale"],
    status: "Flere storrelser",
    link: "click here",
    img: {
      id: "img11",
      path: "/img1.webp",
      alt: "image alt",
    },
  },
  {
    id: "2",
    name: "Hejjen MOda",
    type: "dinning",
    price: "na 230",
    discounted: "na 200",
    sale: ["50%", "limited"],
    status: "Flere storrelser",
    link: "click here",
    img: {
      id: "img13",
      path: "/img3.webp",
      alt: "image alt",
    },
  },
  {
    id: "3",
    name: "Hejjen MOda",
    type: "dinning",
    price: "na 230",
    discounted: "na 200",
    sale: ["sale"],
    status: "Flere storrelser",
    link: "click here",
    img: {
      id: "img144",
      path: "/img4.webp",
      alt: "image alt",
    },
  },
  {
    id: "4",
    name: "Hejjen MOda",
    type: "sofa",
    price: "na 230",
    discounted: "na 200",
    sale: ["70%", "limited"],
    status: "Flere storrelser",
    link: "click here",
    img: {
      id: "img15",
      path: "/sofa5.webp",
      alt: "image alt",
    },
  },
  {
    id: "5",
    name: "Hejjen MOda",
    type: "sofa",
    price: "na 230",
    discounted: "na 200",
    sale: ["70%", "limited"],
    status: "Flere storrelser",
    link: "click here",
    img: {
      id: "img14",
      path: "/sofa4.webp",
      alt: "image alt",
    },
  },
  {
    id: "6",
    name: "Hejjen MOda",
    type: "bed",
    price: "na 230",
    discounted: "na 200",
    sale: ["70%", "limited"],
    status: "Flere storrelser",
    link: "click here",
    img: {
      id: "img143",
      path: "/bed1.webp",
      alt: "image alt",
    },
  },
  {
    id: "7",
    name: "Hejjen MOda",
    type: "bed",
    price: "na 230",
    discounted: "na 200",
    sale: ["70%", "limited"],
    status: "Flere storrelser",
    link: "click here",
    img: {
      id: "img143ww",
      path: "/bed2.webp",
      alt: "image alt",
    },
  },
  {
    id: "8",
    name: "Hejjen MOda",
    type: "bed",
    price: "na 230",
    discounted: "na 200",
    sale: ["70%", "limited"],
    status: "Flere storrelser",
    link: "click here",
    img: {
      id: "img1431",
      path: "/bed3.webp",
      alt: "image alt",
    },
  },
];

export const filterKey = ["bed", "sofa", "dining"];
